title: Houston Lewis
email: houstonhvrd@gmail.com
description: Full Stack Developer
url: https://houstonlws.github.io
baseurl: ""

github: https://github.com/houstonlws
linkedin: https://www.linkedin.com/in/houstonlewis/

# Build settings
plugins:
  - jekyll-feed
